/**
 * Config plugin: fix the `fmt` consteval build error on newer Xcode/Clang.
 *
 * Expo SDK 52 / React Native pins `fmt` at 11.0.2, which uses C++20 `consteval`
 * for compile-time format-string validation. The Clang in EAS's `image: latest`
 * is strict enough to reject fmt's/RN's format-string call sites with:
 *   "call to consteval function 'fmt::basic_format_string<...>' is not a
 *    constant expression"
 *
 * IMPORTANT: the usual `-DFMT_USE_CONSTEVAL=0` compiler-flag fix does NOT work
 * for fmt 11.0.2 — its base.h defines FMT_USE_CONSTEVAL *unconditionally* (no
 * #ifndef guard), so the header redefines it back to 1 on modern clang and the
 * flag is clobbered. We instead patch base.h directly in `post_install` to
 * force FMT_USE_CONSTEVAL to 0, which makes the existing #else branch (already
 * present in the header) set FMT_CONSTEVAL/FMT_CONSTEXPR20 to empty. That turns
 * the offending basic_format_string constructor into an ordinary constructor —
 * compiles cleanly, and RN does not rely on fmt's compile-time validation.
 *
 * ios/ is gitignored and regenerated by `expo prebuild` on EAS, and Pods are
 * re-downloaded each build, so this MUST run as a post_install hook (a one-off
 * header edit would be wiped). The patch is idempotent via a marker comment.
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const POST_INSTALL_MARKER = 'withFmtConstevalFix';
const SNIPPET = `
    # --- withFmtConstevalFix: force fmt's FMT_USE_CONSTEVAL off (Xcode 16+ clang) ---
    fmt_base = File.join(installer.sandbox.root.to_s, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      fmt_src = File.read(fmt_base)
      unless fmt_src.include?('FMT_PATCHED_NO_CONSTEVAL')
        patched = fmt_src.sub(
          "#if FMT_USE_CONSTEVAL\\n#  define FMT_CONSTEVAL consteval",
          "// FMT_PATCHED_NO_CONSTEVAL\\n#undef FMT_USE_CONSTEVAL\\n#define FMT_USE_CONSTEVAL 0\\n#if FMT_USE_CONSTEVAL\\n#  define FMT_CONSTEVAL consteval"
        )
        if patched != fmt_src
          File.write(fmt_base, patched)
          Pod::UI.puts '[withFmtConstevalFix] Patched fmt/base.h — consteval disabled'
        else
          Pod::UI.warn '[withFmtConstevalFix] fmt/base.h anchor not found — fmt version may have changed; check the consteval patch.'
        end
      end
    end
    # --- end withFmtConstevalFix ---
`;

module.exports = function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfile = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfile, 'utf8');

      if (contents.includes(POST_INSTALL_MARKER)) return config; // already injected

      const anchor = /post_install do \|installer\|/;
      if (!anchor.test(contents)) {
        throw new Error(
          'withFmtConstevalFix: could not find "post_install do |installer|" in the Podfile to patch.'
        );
      }
      contents = contents.replace(anchor, (m) => `${m}\n${SNIPPET}`);
      fs.writeFileSync(podfile, contents);
      return config;
    },
  ]);
};
