-- Migration: Add training plans table
-- Description: Stores training plans generated by AI

-- Training plans table
CREATE TABLE IF NOT EXISTS training_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  goal_event TEXT NOT NULL,
  event_date DATE NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  weeks JSONB NOT NULL,
  total_tss INTEGER NOT NULL,
  total_weeks INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_training_plans_athlete ON training_plans(athlete_id);
CREATE INDEX IF NOT EXISTS idx_training_plans_status ON training_plans(athlete_id, status);
CREATE INDEX IF NOT EXISTS idx_training_plans_dates ON training_plans(athlete_id, start_date, end_date);

-- Add training plan reference to calendar entries (optional, for tracking which plan a workout belongs to)
ALTER TABLE calendar_entries ADD COLUMN IF NOT EXISTS training_plan_id UUID REFERENCES training_plans(id) ON DELETE SET NULL;
ALTER TABLE calendar_entries ADD COLUMN IF NOT EXISTS week_number INTEGER;

-- Add training plan reference to workouts (optional, for tracking which plan generated the workout)
ALTER TABLE workouts ADD COLUMN IF NOT EXISTS training_plan_id UUID REFERENCES training_plans(id) ON DELETE SET NULL;

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_training_plans_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER training_plans_updated_at
  BEFORE UPDATE ON training_plans
  FOR EACH ROW
  EXECUTE FUNCTION update_training_plans_updated_at();
